import { StyleSheet } from "react-native";
export default StyleSheet.create({
    container: {
        flex: 1,
      },
      _main: {
        backgroundColor: "#103EF9",
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "space-between",
      },
      _main2: {
        backgroundColor: "#FEAD05",
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "space-between",
      },
      _main3: {
        backgroundColor: "#05C4DE",
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "space-between",
      },
      _main4: {
        backgroundColor: "#FF1178",
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "space-between",
      },
      _main5: {
        backgroundColor: "#8D13FF",
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "space-between",
      },
      _main6: {
        backgroundColor: "#103EF9",
        flex: 1,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "space-between",
      },
      button: {
        alignSelf: "center",
        height: 29,
        marginBottom: 10,
        marginTop: 5,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 20,
        marginHorizontal: 5,
      },
      _button_txt: {
        color: "#000",
        fontSize: 16,
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
      },
      _welcome: {
        color: "white",
        fontSize: 24,
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        marginHorizontal: 30,
        textAlign: "center",
        marginTop: -20,
      },
      _welcomeios: {
        color: "white",
        fontSize: 24,
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        marginHorizontal: 30,
        textAlign: "center",
      },
      _header_main2: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-around",
        backgroundColor: "#000",
        height: 110,
        position: "absolute",
        bottom: 0,
        width: "100%",
      },
      _emoji_main: {
        width: 100,
        height: 100,
        borderRadius: 15,
        alignSelf: "center",
        alignItems: "center",
        justifyContent: "center",
        // marginTop: "10%",
      },
      _emoji: {
        fontSize: 65,
      },
      _tags: {
        color: "#fff",
        textAlign: "center",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 34,
      },
      _Des: {
        color: "#fff",
        textAlign: "center",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
        fontSize: 24,
        marginTop: -10,
      },
      _Desios: {
        color: "#fff",
        textAlign: "center",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
        fontSize: 24,
      },
      _leave_btn_main: {
        alignSelf: "center",
        justifyContent: "center",
        marginBottom: 30,
      },
      _header_main: {
        flexDirection: "row",
        marginTop: 50,
        width: "80%",
        // alignItems: "center",
        justifyContent: "space-between",
      },
      _header_icons_main: {
        alignItems: "center",
      },
      _header_text: {
        color: "#fff",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 18,
        textAlign: "center",
      },
      _btn_main: {
        flexDirection: "row",
        alignItems: "center",
        alignSelf: "center",
      },
      _leave_comment_btn_main: {
        backgroundColor: "#1C1C1E",
        width: "90%",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        borderRadius: 50,
        padding: 15,
        height: 75,
        marginBottom: 20,
      },
      _profile: {
        width: 50,
        height: 50,
        borderRadius: 50 / 2,
      },
      _input: {
        color: "#fff",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 20,
      },
      card_maiin: {
        // borderWidth: 2,
        // borderColor: "#fff",
        width: "100%",
        justifyContent: "center",
      },
      imageStyle: {
        // height: PixelRatio.getPixelSizeForLayoutSize(135),
        width: "100%",
      },
      wrapper: {
        justifyContent: "center",
        alignItems: "center",
        marginVertical: 30,
      },
      header: {
        fontSize: 30,
        fontWeight: "bold",
        marginBottom: 20,
      },
      paragraph: {
        fontSize: 17,
      },
      paginationWrapper: {
        position: "absolute",
        bottom: 200,
        left: 0,
        right: 0,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
      },
      paginationDots: {
        height: 10,
        width: 10,
        borderRadius: 10 / 2,
        backgroundColor: "red",
        marginLeft: 10,
      },
    
      bottom_main: {
        flex: 1,
      },
      b_header_main: {
        flexDirection: "row",
        marginTop: 0,
        alignItems: "center",
        justifyContent: "space-between",
      },
      _header_btn: {
        width: 50,
        height: 50,
        borderRadius: 50 / 2,
        alignItems: "center",
        justifyContent: "center",
      },
      _leave_comment_btn_main: {
        backgroundColor: "#1C1C1E",
        width: "90%",
        minHeight: 75,
        flexDirection: "row",
        justifyContent: "space-between",
        borderRadius: 50,
        padding: 15,
        alignItems: "center",
        alignSelf: "center",
        marginBottom: 30,
      },
      _profile: {
        width: 50,
        height: 50,
        borderRadius: 50 / 2,
      },
      _input2: {
        color: "#fff",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 20,
        width: "60%",
        marginTop: 15,
      },
      _inputios: {
        color: "#fff",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 20,
        width: "60%",
      },
      _profile2: {
        width: 57,
        height: 57,
        borderRadius: 57 / 2,
        alignSelf: "center",
        // marginTop: -30,
      },
      name: {
        color: "#fff",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 16,
        textAlign: "center",
      },
      _location: {
        color: "white",
        textAlign: "center",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
      },
      _body: {
        flex: 1,
        paddingHorizontal: 20,
      },
      comment_counter: {
        color: "#fff",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 18,
        textAlign: "center",
      },
      _comment: {
        color: "#fff",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
        fontSize: 18,
        textAlign: "center",
        marginLeft: 5,
      },
      _card_main: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderTopColor: "#2D2D2D",
        borderTopWidth: 1,
        paddingVertical: 10,
      },
      _card_part1: {
        width: "20%",
      },
      _card_part2: {
        width: "65%",
        paddingRight: 50,
      },
      _card_part3: {
        width: "10%",
        alignItems: "center",
      },
      _card_name: {
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 16,
        marginBottom: -7,
      },
      _card_nameios: {
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
        fontSize: 16,
      },
      _card_message: {
        color: "white",
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
        fontSize: 16,
      },
      _card_time: {
        color: "#FFFFFFB2",
        fontSize: 12,
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
        marginLeft: 20,
      },
      saved_Counter: {
        color: "white",
        fontSize: 12,
        fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
      },
})