import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  _main: {
    backgroundColor: "#103EF9",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _main2: {
    backgroundColor: "#FEAD05",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _main3: {
    backgroundColor: "#05C4DE",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _main4: {
    backgroundColor: "#FF1178",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _main5: {
    backgroundColor: "#8D13FF",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _main6: {
    backgroundColor: "#103EF9",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  button: {
    alignSelf: "center",
    height: 29,
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    marginHorizontal: 5,
  },
  _button_txt: {
    fontSize: 16,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
  },
  _welcome: {
    color: "#000",
    fontSize: 24,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginHorizontal: 30,
    textAlign: "center",
    marginTop: -20,
  },
  _welcomeios: {
    color: "#000",
    fontSize: 24,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginHorizontal: 30,
    textAlign: "center",
  },
  _header_main2: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#000",
    height: 110,
    position: "absolute",
    bottom: 0,
    width: "100%",
  },
  _tags: {
    color: "#000",
    textAlign: "center",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 34,
  },
  _Des: {
    color: "#fff",
    textAlign: "center",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    fontSize: 24,
    marginTop: -10,
  },
  _Desios: {
    color: "#fff",
    textAlign: "center",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    fontSize: 24,
  },
  _leave_btn_main: {
    alignSelf: "center",
    justifyContent: "center",
    marginBottom: 30,
  },
  _header_main: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: -70,
  },
  _header_icons_main: {
    alignItems: "center",
  },
  _header_text: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 18,
    textAlign: "center",
  },
  _btn_main: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    marginBottom:"20%"
  },
  _leave_comment_btn_main: {
    backgroundColor: "#1C1C1E",
    width: "90%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 50,
    padding: 15,
    height: 75,
    marginBottom: 20,
  },
  _profile: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
  },
  _input: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 20,
  },
  card_maiin: {
    flex:1,
    width: "100%",
    justifyContent: "center",
    // height:350,
  
  },
  imageStyle: {
    // height: PixelRatio.getPixelSizeForLayoutSize(135),
    width: "100%",
  },
  wrapper: {
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 30,
  },
  header: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 20,
  },
  paragraph: {
    fontSize: 17,
  },
  paginationWrapper: {
    position: "absolute",
    bottom: 200,
    left: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  paginationDots: {
    height: 10,
    width: 10,
    borderRadius: 10 / 2,
    backgroundColor: "red",
    marginLeft: 10,
  },

  bottom_main: {
    flex: 1,
  },
  b_header_main: {
    flexDirection: "row",
    marginTop: 0,
    alignItems: "center",
    justifyContent: "space-between",
  },
  _header_btn: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
    alignItems: "center",
    justifyContent: "center",
  },
  _leave_comment_btn_main: {
    backgroundColor: "#1C1C1E",
    width: "90%",
    minHeight: 75,
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 50,
    padding: 15,
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 30,
  },
  _profile: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
  },
  _input2: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 20,
    width: "70%",
    marginTop: 15,
    marginLeft:20
  },
  _inputios: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 20,
    width: "70%",
    marginLeft:20
  },
  _profile2: {
    width: 57,
    height: 57,
    borderRadius: 57 / 2,
    alignSelf: "center",
    // marginTop: -30,
  },
  name: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 16,
    textAlign: "center",
  },
  _location: {
    color: "white",
    textAlign: "center",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
  },
  _body: {
    flex: 1,
    paddingHorizontal: 20,
  },
  comment_counter: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 18,
    textAlign: "center",
  },
  _comment: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    fontSize: 18,
    textAlign: "center",
    marginLeft: 5,
  },
  _card_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopColor: "#2D2D2D",
    borderTopWidth: 1,
    paddingVertical: 10,
  },
  _card_part1: {
    width: "20%",
  },
  _card_part2: {
    width: "65%",
    paddingRight: 50,
  },
  _card_part3: {
    width: "10%",
    alignItems: "center",
  },
  _card_name: {
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 16,
    marginBottom: -7,
  },
  _card_nameios: {
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 16,
  },
  _card_message: {
    color: "white",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    fontSize: 16,
  },
  _card_time: {
    color: "#FFFFFFB2",
    fontSize: 12,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    marginLeft: 20,
  },
  saved_Counter: {
    color: "white",
    fontSize: 12,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
  },
  slider_profile: {
    width: 75,
    height: 75,
    borderRadius: 75 / 2,
    alignSelf: "center",
    marginTop:"10%"
  },
  user_name: {
    color: "white",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    textAlign: "center",
    fontSize: 20,
  },
  _address: {
    color: "#000",
    fontSize: 16,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    textAlign: "center",
  },
  _data_counter_main: {
    flex: 1,
    backgroundColor: "#000",
    width: "100%",
  },
  _data_counter_rouder: {
    width: 100,
    height: 100,
    backgroundColor: "#000",
    borderRadius: 100 / 2,
    alignSelf: "center",
    marginTop: -20,
  },
  _after_counter_messsage: {
    color: "#fff",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    textAlign: "center",
    fontSize: 20,
    marginTop: 5,
  },
});
