import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "red",
  },
  _main: {
    backgroundColor: "#000",
    flex: 1,
    paddingHorizontal: 20,
  },
  _heading: {
    color: "white",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginTop: 20,
  },
  _sub_heading: {
    color: "#09F9BF",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginBottom: 10,
    marginTop: -25,
  },
  _sub_headingiOS: {
    color: "#09F9BF",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginBottom: 10,
  },
  _input_main: {
    backgroundColor: "#1C1C1E",
    height: 62,
    borderRadius: 10,
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  _input: {
    width: "85%",
    fontSize: 20,
    color: "white",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    marginBottom: -10,
  },
  _logo: {
    alignSelf: "center",
    marginTop: 30,
  },
  _login_button_txt: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    alignSelf: "center",
    marginTop: 10,
  },
  _bottom_heading: {
    color: "#fff",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginTop: -15,
  },
  _bottom_sub_heading: {
    color: "#00E0FF",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginTop: -25,
  },
  _bottom_sub_heading2: {
    color: "#FF4D4D",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginTop: -25,
  },
  _bottom_sub_headingiOS: {
    color: "#00E0FF",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
  },
  _bottom_sub_headingiOS2: {
    color: "#FF4D4D",
    textAlign: "center",
    fontSize: 34,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
  },
  _bottom_sheet_main: {
    marginHorizontal: 20,
  },
  _gps_main: {
    backgroundColor: "#1C1C1E",
    height: 62,
    borderRadius: 10,
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  _gps_heading: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginLeft: 20,
  },
  _bottom_sheet_des: {
    color: "#fff",
    fontSize: 22,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    textAlign: "center",
    marginTop: 10,
  },
});
