import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor:"#0D0D0D"
  },
  _main: {
    backgroundColor: "#0D0D0D",
    flex: 1,
    paddingHorizontal: 20,
    alignItems: "center",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heading: {
    color: "white",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 34,
  },
  _des: {
    color: "white",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Light",
    fontSize: 18,
    alignSelf: "center",
  },
  _terms_btn_text: {
    color: "white",
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    fontSize: 18,
  },
  _des_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: -10,
    marginBottom: 20,
  },
  logo: {
    marginTop: 10,
    alignItems:"center"
  },
  _bottom_sheet_main: {},
  _bottom_sheet_heading: {
    color: "white",
    fontSize: 20,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    textAlign: "center",
  },
  email_button: {
    width: 270,
    flexDirection: "row",
    alignSelf: "center",
    height: 50,
    marginTop: 20,
    backgroundColor: "white",
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  email_button_txt: {
    color: "#000",
    fontSize: 20,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginLeft: 10,
  },
  twitter_button: {
    width: 270,
    flexDirection: "row",
    alignSelf: "center",
    height: 50,
    marginTop: 20,
    backgroundColor: "#1D9BF0",
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  twitter_button_txt: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginLeft: 10,
  },
  google_button: {
    width: 270,
    flexDirection: "row",
    alignSelf: "center",
    height: 50,
    marginTop: 20,
    backgroundColor: "#D4D8DD",
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  apple_button: {
    width: 270,
    flexDirection: "row",
    alignSelf: "center",
    height: 50,
    marginTop: 20,
    marginBottom: 5,
    borderWidth: 1,
    borderColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
  },
  apple_button_txt: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    marginLeft: 10,
  },
  close_button_txt: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "FontsFree-Net-SF-Pro-Rounded-Black",
    textAlign: "center",
    marginTop: 20,
  },
});
